version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "127.0.0.1:1001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
    volumes:
      - my-datavolume:/var/lib/mysql
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "127.0.0.1:1002:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
volumes:
  my-datavolume: